### ISSUE TITLE
reduce matched rules

### ISSUE THREAD

**Issue by tbela99** [tbela99/critical#18]
for a matched rule

```css
.container, .container-fluid, .container-lg, .container-md, .container-sm, .container-xl, .container-xxl { --bs-gutter-x: 1.5rem; }
```

if the only selector matched is '.container' then reduce it to

```css
.container { --bs-gutter-x: 1.5rem}
```
